eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
      
---
spring:
  profiles: sentences
server:
  port: 8020
words: NotImplemented

---
spring:
  profiles: subject
words: I,He,She

---
spring:
  profiles: verb
words: eat,sleep,drink
